[Line 0]: [L0 Format some-test] Exception caught!
Traceback (most recent call last):
  File "/Users/busramarsan/Downloads/validation task/boun-treebank-evaluation/util/validate.py", line 3031, in <module>
    open_files.append(io.open(fname, 'r', encoding='utf-8'))
FileNotFoundError: [Errno 2] No such file or directory: 'tr_boun_v2-train.conllu'
Format errors: 1
*** FAILED *** with 1 errors
